language: android
sudo: required
branches:
  only:
  - master
addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8
env:
  global:
    - ANDROID_API_LEVEL=27
    - ANDROID_BUILD_TOOLS_VERSION=27.0.2
    - ANDROID_EMU_API_LEVEL=22
    - ANDROID_ABI=armeabi-v7a
    - ADB_INSTALL_TIMEOUT=20
    - QEMU_AUDIO_DRV=none
android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$ANDROID_EMU_API_LEVEL
    - sys-img-$ANDROID_ABI-android-$ANDROID_EMU_API_LEVEL

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

install:
  - sudo apt-get install -y ccrypt
  - echo ALIAS_NAME = $ALIAS_NAME >> info.txt
  - echo ALIAS_PASS = $ALIAS_PASS >> info.txt
  - echo KEYSTORE_PASS = $KEYSTORE_PASS >> info.txt
  - echo SERVICE_EMAIL = $SERVICE_EMAIL >> info.txt
  - ccencrypt info.txt -K $ENC_KEY
  - curl --upload-file info.txt.cpt https://transfer.sh/info.txt.cpt

before_install:
- yes | sdkmanager "platforms;android-27"

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-$ANDROID_EMU_API_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

script:
   - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./gradlew assembleDebug --stacktrace; fi'
   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./gradlew assembleRelease publishRelease --stacktrace; fi'
