include: package:pedantic/analysis_options.1.8.0.yaml

linter:
  rules:
    - unnecessary_const
    - prefer_const_declarations
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables