include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - tools/**

plugins:
  dependency_overrides:
    analysis_server_plugin: '0.3.15'
  tautulli_lints:
    path: tools/tautulli_lints

linter:
  rules:
    unnecessary_const: true
    prefer_const_declarations: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    depend_on_referenced_packages: false
    use_build_context_synchronously: false

formatter:
  page_width: 120
  trailing_commas: preserve