name: tautulli_remote
description: An application for accessing your Tautulli server remotely.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.12.3+124

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  app_group_directory: ^2.0.0
  cached_network_image: ^3.1.0
  collection: ^1.15.0-nullsafety.4
  color: ^3.0.0
  connectivity_plus: ^1.0.6
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0
  device_info_plus: ^2.1.0
  duration: ^3.0.6
  easy_localization: ^3.0.0
  equatable: ^2.0.3
  expandable: ^5.0.1
  f_logs: ^2.0.0
  filesize: ^2.0.1
  firebase_core: ^1.4.0
  fl_chart: ^0.36.3
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^7.1.0
  flutter_cache_manager: ^3.1.2
  flutter_card_swipper: ^0.4.0
  flutter_inner_drawer:
    git: https://github.com/TheMeanCanEHdian/flutter_inner_drawer.git
  flutter_slidable: ^0.6.0
  flutter_sticky_header: ^0.6.0
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^9.1.0
  get_it: ^7.2.0
  http: ^0.13.3
  intl: ^0.17.0
  onesignal_flutter: ^3.2.0
  package_info_plus: ^1.0.4
  palette_generator: ^0.3.0
  path_provider: ^2.0.2
  permission_handler: ^8.1.4+2
  purchases_flutter: ^3.4.1
  quiver: ^3.0.1
  reorderables: ^0.4.1
  rxdart: ^0.27.1
  shared_preferences: ^2.0.6
  simple_moment: ^1.1.1
  sqflite: ^2.0.0+3
  url_launcher: ^6.0.9
  validators: ^3.0.0
  version: ^2.0.0
  websafe_svg: ^2.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^1.0.4
  flutter_native_splash: ^1.2.1
  flutter_test:
    sdk: flutter
  mockito: ^5.0.14

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "dev_assets/logo.png"
  adaptive_icon_background: "#292b2f"
  adaptive_icon_foreground: "dev_assets/logo-adaptive.png"

flutter_native_splash:
  color: "#292b2f"
  image: assets/splash/splash_ios.png
  android: false
  web: false

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/platforms/alexa.svg
    - assets/platforms/android.svg
    - assets/platforms/atv.svg
    - assets/platforms/chrome.svg
    - assets/platforms/chromecast.svg
    - assets/platforms/default.svg
    - assets/platforms/dlna.svg
    - assets/platforms/firefox.svg
    - assets/platforms/ie.svg
    - assets/platforms/ios.svg
    - assets/platforms/kodi.svg
    - assets/platforms/lg.svg
    - assets/platforms/linux.svg
    - assets/platforms/macos.svg
    - assets/platforms/msedge.svg
    - assets/platforms/opera.svg
    - assets/platforms/playstation.svg
    - assets/platforms/plex.svg
    - assets/platforms/plexamp.svg
    - assets/platforms/roku.svg
    - assets/platforms/safari.svg
    - assets/platforms/samsung.svg
    - assets/platforms/synclounge.svg
    - assets/platforms/tivo.svg
    - assets/platforms/windows.svg
    - assets/platforms/xbox.svg
    - assets/libraries/artist.svg
    - assets/libraries/movie.svg
    - assets/libraries/photo.svg
    - assets/libraries/show.svg
    - assets/icons/concurrent.svg
    - assets/images/livetv_fallback.png
    - assets/images/default_profile.png
    - assets/logo/logo.png
    - assets/logo/logo_transparent.png
    - assets/splash/splash_ios.png
    - assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Italic.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
