name: tautulli_remote
description: An application for accessing your Tautulli server remotely.

publish_to: 'none'

version: 3.0.0-alpha.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  onesignal_flutter: ^3.2.7

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_native_splash: ^1.2.3
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "dev_assets/logo.png"
  adaptive_icon_background: "#292b2f"
  adaptive_icon_foreground: "dev_assets/logo-adaptive.png"

flutter_native_splash:
  color: "#292b2f"
  image: assets/splash/splash_ios.png
  android: false
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/platforms/alexa.svg
    - assets/platforms/android.svg
    - assets/platforms/atv.svg
    - assets/platforms/chrome.svg
    - assets/platforms/chromecast.svg
    - assets/platforms/default.svg
    - assets/platforms/dlna.svg
    - assets/platforms/firefox.svg
    - assets/platforms/ie.svg
    - assets/platforms/ios.svg
    - assets/platforms/kodi.svg
    - assets/platforms/lg.svg
    - assets/platforms/linux.svg
    - assets/platforms/macos.svg
    - assets/platforms/msedge.svg
    - assets/platforms/opera.svg
    - assets/platforms/playstation.svg
    - assets/platforms/plex.svg
    - assets/platforms/plexamp.svg
    - assets/platforms/roku.svg
    - assets/platforms/safari.svg
    - assets/platforms/samsung.svg
    - assets/platforms/synclounge.svg
    - assets/platforms/tivo.svg
    - assets/platforms/windows.svg
    - assets/platforms/xbox.svg
    - assets/libraries/artist.svg
    - assets/libraries/movie.svg
    - assets/libraries/photo.svg
    - assets/libraries/show.svg
    - assets/icons/concurrent.svg
    - assets/images/livetv_fallback.png
    - assets/images/default_profile.png
    - assets/logo/logo.png
    - assets/logo/logo_transparent.png
    - assets/splash/splash_ios.png
    - assets/translations/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Italic.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
