name: tautulli_remote
description: An application for accessing your Tautulli server remotely.

publish_to: 'none'

version: 3.3.0+167

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  android_id: ^0.4.0
  app_group_directory: ^2.0.0
  app_version_update: ^5.0.3
  badges: ^3.1.2
  bloc_concurrency: ^0.2.5
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.0.5
  cryptography_flutter: ^2.3.2
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_info_plus: ^10.1.2
  dio: ^5.7.0
  draggable_scrollbar: ^0.1.0
  duration: ^4.0.3
  easy_localization: ^3.0.7
  equatable: ^2.0.5
  f_logs:
    git:
      url: https://github.com/TheMeanCanEHdian/Flogs.git
      ref: tautulli-remote
  filesize: ^2.0.1
  fl_chart: ^0.69.0
  flex_seed_scheme: ^3.3.0
  flutter:
    sdk: flutter
  flutter_barcode_scanner:
    git: https://github.com/TheMeanCanEHdian/flutter_barcode_scanner.git
  flutter_bloc: ^8.1.3
  flutter_cache_manager: ^3.4.1
  flutter_colorpicker: ^1.1.0
  flutter_inner_drawer:
    git: https://github.com/TheMeanCanEHdian/flutter_inner_drawer.git
  flutter_platform_widgets: ^7.0.1
  flutter_sticky_header: ^0.6.5
  fluttertoast: ^8.2.8
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  im_stepper: ^1.0.1+1
  json_annotation: ^4.9.0
  onesignal_flutter: ^3.5.3
  package_info_plus: ^8.0.2
  palette_generator: ^0.3.3+4
  path_provider: ^2.1.4
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.1
  # purchases_flutter: ^6.18.0
  quick_actions: ^1.0.7
  quiver: ^3.2.2
  rate_my_app: ^2.0.0
  reorderables: ^0.6.0
  share_plus: ^10.0.2
  shared_preferences: ^2.3.2
  shorebird_code_push: ^1.1.4
  simple_moment: ^1.1.1
  sqflite: ^2.3.3+1
  stream_transform: ^2.1.0
  system_theme: ^3.1.1
  url_launcher: ^6.3.0
  validators: ^3.0.0
  version: ^3.0.2
  websafe_svg: ^3.0.1+2

dependency_overrides:
  intl: ^0.18.0

dev_dependencies:
  build_runner: ^2.4.12
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "dev_assets/logo.png"
  adaptive_icon_background: "#292b2f"
  adaptive_icon_foreground: "dev_assets/logo-adaptive.png"

flutter_native_splash:
  color: "#292b2f"
  image: assets/splash/splash_ios.png
  android: false
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/platforms/alexa.svg
    - assets/platforms/android.svg
    - assets/platforms/atv.svg
    - assets/platforms/chrome.svg
    - assets/platforms/chromecast.svg
    - assets/platforms/default.svg
    - assets/platforms/dlna.svg
    - assets/platforms/firefox.svg
    - assets/platforms/ie.svg
    - assets/platforms/ios.svg
    - assets/platforms/kodi.svg
    - assets/platforms/lg.svg
    - assets/platforms/linux.svg
    - assets/platforms/macos.svg
    - assets/platforms/msedge.svg
    - assets/platforms/opera.svg
    - assets/platforms/playstation.svg
    - assets/platforms/plex.svg
    - assets/platforms/plexamp.svg
    - assets/platforms/roku.svg
    - assets/platforms/safari.svg
    - assets/platforms/samsung.svg
    - assets/platforms/synclounge.svg
    - assets/platforms/tivo.svg
    - assets/platforms/windows.svg
    - assets/platforms/xbox.svg
    - assets/libraries/artist.svg
    - assets/libraries/movie.svg
    - assets/libraries/live.svg
    - assets/libraries/photo.svg
    - assets/libraries/playlist.svg
    - assets/libraries/show.svg
    - assets/libraries/video.svg
    - assets/icons/concurrent.svg
    - assets/images/default_profile.png
    - assets/images/art_error.png
    - assets/images/art_fallback.png
    - assets/images/cover_error.png
    - assets/images/cover_fallback.png
    - assets/images/livetv_fallback.png
    - assets/images/poster_error.png
    - assets/images/poster_fallback.png
    - assets/logos/logo.png
    - assets/logos/logo_transparent.png
    - assets/logos/logo_flat.svg
    - assets/logos/weblate.svg
    - assets/logos/onesignal.svg
    - assets/splash/splash_ios.png
    - assets/translations/
    - shorebird.yaml
