name: tautulli_remote_tdd
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0-dev.3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Bloc for state management
  flutter_bloc: ^5.0.1
  # To send various requests to URLs
  http: ^0.12.1
  # Value equality
  equatable: ^1.2.2
  # Functional programming
  dartz: ^0.9.1
  # Verifies network connectivity
  connectivity: '>=0.4.9 <2.0.0'
  # Service locator
  get_it: ^4.0.2
  # Local storage
  shared_preferences: '>=0.5.8 <2.0.0'
  # SQL database for local storage
  sqflite: ^1.3.1
  # Used to convert RGB to HEX
  color: ^2.1.1
  # Used to access Font Awesome icons
  font_awesome_flutter: ^8.8.1
  # Pretty durations
  duration: ^2.0.15
  # Internationalization and localization
  intl: ^0.16.1
  # Slidable list items
  flutter_slidable: ^0.5.4
  # SVG support
  websafe_svg: ^1.1.0
  # Utility libraries
  quiver: ^2.1.3
  # Barcode scanner
  flutter_barcode_scanner: ^1.0.1
  # Notifications
  onesignal_flutter: ^2.6.0
  # Get current device info
  device_info: '>=0.4.2+4 <2.0.0'
  # For launching URLs
  url_launcher: ^5.5.0
  # Logging
  f_logs: ^1.2.2
  # Permission handling
  permission_handler: ^5.0.1+1
  # For finding commonly used locations on the filesystem
  path_provider: ^1.6.11
  # For creating a FAB speed dial
  unicorndial: ^1.1.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  # Simplifies launcher icon creation
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: true
  ios: true
  image_path: "dev_assets/logo.png"
  adaptive_icon_background: "#292b2f"
  adaptive_icon_foreground: "dev_assets/logo-adaptive.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/platforms/android.svg
   - assets/platforms/atv.svg
   - assets/platforms/chrome.svg
   - assets/platforms/chromecast.svg
   - assets/platforms/default.svg
   - assets/platforms/dlna.svg
   - assets/platforms/firefox.svg
   - assets/platforms/ie.svg
   - assets/platforms/ios.svg
   - assets/platforms/kodi.svg
   - assets/platforms/lg.svg
   - assets/platforms/linux.svg
   - assets/platforms/macos.svg
   - assets/platforms/msedge.svg
   - assets/platforms/opera.svg
   - assets/platforms/playstation.svg
   - assets/platforms/plex.svg
   - assets/platforms/plexamp.svg
   - assets/platforms/roku.svg
   - assets/platforms/safari.svg
   - assets/platforms/samsung.svg
   - assets/platforms/synclounge.svg
   - assets/platforms/tivo.svg
   - assets/platforms/windows.svg
   - assets/platforms/xbox.svg
   - assets/images/livetv_fallback.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Italic.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
