name: tautulli_remote
description: An application for accessing your Tautulli server remotely.

publish_to: 'none'

version: 3.0.0-alpha.18

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  android_id: ^0.0.7
  app_group_directory: ^2.0.0
  badges: ^2.0.3
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.2.1
  color: ^3.0.0
  connectivity_plus: ^2.3.6+1
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  device_info_plus: ^4.1.2
  dio: ^4.0.6
  duration: ^3.0.11
  easy_localization: ^3.0.1
  equatable: ^2.0.5
  f_logs: ^2.0.1
  fl_chart: ^0.55.1
  flutter:
    sdk: flutter
  flutter_barcode_scanner:
    git: https://github.com/TheMeanCanEHdian/flutter_barcode_scanner.git
  flutter_bloc: ^8.1.1
  flutter_cache_manager: ^3.3.0
  flutter_inner_drawer:
    git: https://github.com/TheMeanCanEHdian/flutter_inner_drawer.git
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  gap: ^2.0.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  http: ^0.13.5
  im_stepper: ^1.0.1+1
  json_annotation: ^4.6.0
  onesignal_flutter: ^3.4.1
  package_info_plus: ^1.4.3+1
  palette_generator: ^0.3.3+1
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  purchases_flutter: ^3.10.0
  quick_actions: ^0.6.0+11
  quiver: ^3.1.0
  reorderables: ^0.5.0
  shared_preferences: ^2.0.15
  simple_moment: ^1.1.1
  sqflite: ^2.0.3+1
  stream_transform: ^2.0.0
  url_launcher: ^6.1.5
  validators: ^3.0.0
  version: ^3.0.2
  websafe_svg: ^2.1.2+2

dev_dependencies:
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.8
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "dev_assets/logo.png"
  adaptive_icon_background: "#292b2f"
  adaptive_icon_foreground: "dev_assets/logo-adaptive.png"

flutter_native_splash:
  color: "#292b2f"
  image: assets/splash/splash_ios.png
  android: false
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/platforms/alexa.svg
    - assets/platforms/android.svg
    - assets/platforms/atv.svg
    - assets/platforms/chrome.svg
    - assets/platforms/chromecast.svg
    - assets/platforms/default.svg
    - assets/platforms/dlna.svg
    - assets/platforms/firefox.svg
    - assets/platforms/ie.svg
    - assets/platforms/ios.svg
    - assets/platforms/kodi.svg
    - assets/platforms/lg.svg
    - assets/platforms/linux.svg
    - assets/platforms/macos.svg
    - assets/platforms/msedge.svg
    - assets/platforms/opera.svg
    - assets/platforms/playstation.svg
    - assets/platforms/plex.svg
    - assets/platforms/plexamp.svg
    - assets/platforms/roku.svg
    - assets/platforms/safari.svg
    - assets/platforms/samsung.svg
    - assets/platforms/synclounge.svg
    - assets/platforms/tivo.svg
    - assets/platforms/windows.svg
    - assets/platforms/xbox.svg
    - assets/libraries/artist.svg
    - assets/libraries/movie.svg
    - assets/libraries/live.svg
    - assets/libraries/photo.svg
    - assets/libraries/playlist.svg
    - assets/libraries/show.svg
    - assets/libraries/video.svg
    - assets/icons/concurrent.svg
    - assets/images/default_profile.png
    - assets/images/art_fallback.png
    - assets/images/cover_fallback.png
    - assets/images/livetv_fallback.png
    - assets/images/poster_fallback.png
    - assets/logos/logo.png
    - assets/logos/logo_transparent.png
    - assets/logos/logo_flat.svg
    - assets/logos/weblate.svg
    - assets/logos/onesignal.svg
    - assets/splash/splash_ios.png
    - assets/translations/
