name: Bug Report
description: Please do not use bug reports for support issues
labels: [bug, needs-review]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Note: Please use [Discord](https://tautulli.com/discord) for support issues.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List each action required in order to reproduce the issue.
      placeholder: |
        1. Go to [...]
        2. Tap on [...]
        3. Scroll down to [...]
        4. See error
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
  - type: input
    id: version-tautulli-remote
    attributes:
      label: Tautulli Remote Version
      description: What version of Tautulli Remote are you running?
      placeholder: ex. v2.11.2
    validations:
      required: true
  - type: input
    id: version-tautulli
    attributes:
      label: Tautulli Version
      description: What version of Tautulli are you running?
      placeholder: ex. v2.7.5
    validations:
      required: true
  - type: input
    id: mobile-device
    attributes:
      label: Mobile Device
      description: What device are you using?
      placeholder: ex. Pixel 5, iPhone 12
    validations:
      required: true
  - type: input
    id: mobile-os
    attributes:
      label: Mobile OS
      description: What OS version is your device running?
      placeholder: ex. Android 11, iOS 14
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
