name: New Language
description: Request a new language for Tautulli Remote
title: "Add <replace-with-your-language> language"
labels: [new-language]
body:
  - type: checkboxes
    id: verify
    attributes:
      label: Have you verified that the language is not already supported?
      description: Please make sure this language is not already supported but has [no translations on Weblate](https://hosted.weblate.org/projects/tautulli-remote/translations/).
      options:
        - label: I have verified this language is not currently supported
          required: true
