// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAhCOF17B9HL8p7v0GxWUofZtJYSBPu20',
    appId: '1:159358117861:android:4b8cc97ee56a82b547310c',
    messagingSenderId: '159358117861',
    projectId: 'plexpy-remote',
    databaseURL: 'https://plexpy-remote.firebaseio.com',
    storageBucket: 'plexpy-remote.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPAtktHg9O0q4REUA170OBKEG-Ik3m08U',
    appId: '1:159358117861:ios:bbb939efb62f33b547310c',
    messagingSenderId: '159358117861',
    projectId: 'plexpy-remote',
    databaseURL: 'https://plexpy-remote.firebaseio.com',
    storageBucket: 'plexpy-remote.firebasestorage.app',
    androidClientId: '159358117861-15pqrqsltvqas03ev3qjrrdplrr1na0b.apps.googleusercontent.com',
    iosClientId: '159358117861-jsrh66gu2c1qpgl9br8j0tnj1b7bve4d.apps.googleusercontent.com',
    iosBundleId: 'com.tautulli.tautulliRemote',
  );
}
